.c9/metadata/workspace/polls/urls.py
{"filter":false,"title":"urls.py","tooltip":"/polls/urls.py","undoManager":{"mark":-1,"position":-1,"stack":[]},"ace":{"folds":[],"scrolltop":0,"scrollleft":0,"selection":{"start":{"row":8,"column":65},"end":{"row":8,"column":65},"isBackwards":false},"options":{"guessTabSize":true,"useWrapMode":false,"wrapToView":true},"firstLineState":{"row":13,"mode":"ace/mode/python"}},"timestamp":1511331417624,"hash":"685521d4703dce66ddf095c6e6d2f037edc66222"}

.c9/metadata/workspace/usu2610hw2/urls.py
{"filter":false,"title":"urls.py","tooltip":"/usu2610hw2/urls.py","undoManager":{"mark":3,"position":3,"stack":[[{"start":{"row":22,"column":12},"end":{"row":22,"column":13},"action":"remove","lines":["y"],"id":260}],[{"start":{"row":22,"column":11},"end":{"row":22,"column":12},"action":"remove","lines":["m"],"id":261}],[{"start":{"row":22,"column":11},"end":{"row":22,"column":12},"action":"remove","lines":["B"],"id":262}],[{"start":{"row":22,"column":11},"end":{"row":22,"column":12},"action":"insert","lines":["b"],"id":263}]]},"ace":{"folds":[],"scrolltop":36,"scrollleft":0,"selection":{"start":{"row":23,"column":1},"end":{"row":23,"column":1},"isBackwards":false},"options":{"guessTabSize":true,"useWrapMode":false,"wrapToView":true},"firstLineState":0},"timestamp":1511322075379,"hash":"a25de4e964c741bcdc752d2e124485b58fbfc967"}

blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.indexView.as_view(), name='index'),
    url(r'^archive/$', views.archiveView.as_view(), name='archive'),
    url(r'^(?P<pk>[0-9]+)/$', views.detailView.as_view(), name='blog'),
    url(r'^(?P<pk>[0-9]+)/comment/$', views.post, name='post'),
]

polls/urls.py
from django.conf.urls import url
from . import views

app_name = 'polls'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

usu2610hw2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),
]

.c9/metadata/workspace/blog/models.py
{"filter":false,"title":"models.py","tooltip":"/blog/models.py","undoManager":{"mark":-1,"position":-1,"stack":[]},"ace":{"folds":[],"scrolltop":0,"scrollleft":0,"selection":{"start":{"row":10,"column":32},"end":{"row":10,"column":32},"isBackwards":false},"options":{"guessTabSize":true,"useWrapMode":false,"wrapToView":true},"firstLineState":0},"timestamp":1511327949835,"hash":"f9a2b48a8c9a180787d99e04f24e193e34b6b7d1"}

.c9/metadata/workspace/polls/models.py
{"filter":false,"title":"models.py","tooltip":"/polls/models.py","undoManager":{"mark":-1,"position":-1,"stack":[]},"ace":{"folds":[],"scrolltop":0,"scrollleft":0,"selection":{"start":{"row":9,"column":22},"end":{"row":9,"column":22},"isBackwards":false},"options":{"guessTabSize":true,"useWrapMode":false,"wrapToView":true},"firstLineState":{"row":1,"state":"start","mode":"ace/mode/python"}},"timestamp":1510013068257,"hash":"e87a1469cf303d5a5840b8f62bfc34c12fa55ab4"}

blog/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Blog(models.Model):
    def __str__(self):
        return self.title
    title = models.CharField(max_length=200)
    authors_name = models.CharField(max_length=50)
    content = models.TextField()
    posted_date=models.DateTimeField('date published')
    
class Comment(models.Model):
    def __str__(self):
        return self.content
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=50)
    email = models.EmailField
    content = models.TextField()
    posted_date=models.DateTimeField('date published')

polls/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

import datetime

# Create your models here.
class Question(models.Model):
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
class Choice(models.Model):
    def __str__(self):
        return self.choice_text
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

.c9/metadata/workspace/polls/views.py
{"filter":false,"title":"views.py","tooltip":"/polls/views.py","undoManager":{"mark":-1,"position":-1,"stack":[]},"ace":{"folds":[],"scrolltop":192,"scrollleft":0,"selection":{"start":{"row":21,"column":4},"end":{"row":21,"column":4},"isBackwards":false},"options":{"guessTabSize":true,"useWrapMode":false,"wrapToView":true},"firstLineState":{"row":13,"state":"start","mode":"ace/mode/python"}},"timestamp":1510114829521,"hash":"8e37f06762d2f8e8dc28684b04b4ee3bd0b27e67"}

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from models import Blog, Comment
from django.core.urlresolvers import reverse
from django.views import generic
# Create your views here.

class indexView(generic.ListView):
    template_name='blog/index.html'
    context_object_name='blogs'
    
    def get_queryset(self):
        return Blog.objects.order_by('-posted_date')[:3]
        
class archiveView(generic.ListView):
    template_name='blog/archive.html'
    context_object_name='blogs'
    
    def get_queryset(self):
        return Blog.objects.order_by('-posted_date')
    
class detailView(generic.DetailView): 
    model=Blog
    template_name='blog/detail.html'
    
def post(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    try:
        _post = Blog.comment_set.get(pk=request.POST['comment'])
    except (KeyError, comment.DoesNotExist):
        return render(request, 'blog/detail.html', {
            'comment':comment,
            'error_message': "Invalid input",
        })
    else:
        _post.save()
        return HttpResponseRedirect(reverse('index', args=(blog.id)))

polls/views.py
#from django.shortcuts import render
from django.http import HttpResponseRedirect
from models import Question, Choice
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.views import generic

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    
    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model=Question
    template_name= 'polls/detail.html'
    
class ResultsView(generic.DetailView):
    model=Question
    template_name='polls/results.html'
    
    
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question':question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

blog/templates/blog/archive.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />

<!-- FIX THIS, IF BLOGS -->
{% if blogs %}
    {% for blog in blogs %}
    <div id="blogset">
        <!-- title, authors_name, content, posted_date-->
        <h3><a href="{% url 'blog:blog' blog.id %}">{{blog.title}}</a></h3>
        <h4>{{blog.authors_name}}    {{blog.posted_date}}</h4>
        <p>{{blog.content | truncatewords:200}}</p>
        <h4>There are <a href="{% url 'blog:blog' blog.id %}">XX comments</a></h4>
    </div>
    {% endfor %}
    
    
{% else %}
    <p>There are no blog posts yet on this site</p>
{% endif %}

blog/templates/blog/detail.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />

<h1>{{blog.title}}</h1>
<p>{{blog.content}}</p>
<h3>Comments</h3>
<!-- For comments in chrono order -->
{% for comment in blog.comment_set.all %}
    <div id="blogset">
        <h4>{{comment.nickname}}</h4>
        <p>{{comment.content}}</p>
    </div>
{% endfor %}
<form action="{% url 'blog:post' blog.id %}" method="post">
{% csrf_token %}
    <label for="nickname">Nickname:</label>
    <input type="text" name='nickname' value="{{comment.nickname}}"> <br />
    <label for="email">Email:</label>
    <input type='email' name="email" value={{comment.email}}> <br />
    <label for="text">Comment: </label> 
    <input type='textarea' rows=10 name="content" id="text" value={{comment.content}} /> <br />
<input type="submit" value="Comment (This will not work, and, i believe is the only not working part)" />
</form>

blog/templates/blog/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />

{% if blogs %}
    {% for blog in blogs %}
    <div id="blogset">
        <!-- title, authors_name, content, posted_date-->
        <h3><a href="{% url 'blog:blog' blog.id %}">{{blog.title}}</a></h3>
        <h4>{{blog.authors_name}}    {{blog.posted_date}}</h4>
        <p>{{blog.content | truncatewords:200}}</p>        
        <h4>There are <a href="{% url 'blog:blog' blog.id %}">{{ blog.comment_set.count}} comments</a></h4>
    </div>
    {% endfor %}
    
    
{% else %}
    <p>There are no blog posts yet on this site</p>
{% endif %}